server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    discovery:
      enabled: true
    gateway:
      discovery:
        locator:
          enabled: true #worked without
          lowerCaseServiceId: true
      routes:
        - id: userModule
          uri: lb://user-service
          predicates:
            - Path=/users/**
        - id: linksModule
          uri: lb://links-service
          predicates:
            - Path=/links/**

eureka:
  instance:
    #    hostname: localhost
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5
    lease-expiration-duration-in-seconds: 5
  client:
    fetchRegistry: true
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org.springframework.web: INFO
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} - %-4level [${spring.application.name},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{mdcKey},%X{mdcUser},%X{mdcOrigin}] [%X{X-B3-ParentSpanId}] %logger{36} - %m%n%rEx{full,reactor.core.publisher,org.springframework.cloud.sleuth,reactor.ipc.netty,sun.reflect,org.springframework.web.reactive,io.netty.channel}"