spring:
  application:
    name: user-service
  datasource:
#    url: jdbc:h2:file:/data/demo for File Persistence
    url: jdbc:h2:mem:testdb:server
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

#management:
#  endpoints:
#    web:
#      exposure:
#        include: health
