spring:
  application:
    name: discovery-service

server:
  port: 8761

eureka:
  server:
    enableSelfPreservation: true
  instance:
    hostname: localhost
    preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka